- name: Configure Redis
  hosts: Redis
  become: yes
  tasks:
  - name: Enable redis version
    ansible.builtin.command: dnf module enable redis:7 -y
  
  - name: Install Redis
    ansible.builtin.dnf:
     name: redis
     state: present
  
  - name: Allowing remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  
  - name: Disabling protected module
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'

  - name: Enable and start a redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: true